import { App } from "vue";
import {
  Button,
  Icon,
  Menu,
  Pagination,
  Form,
  Input,
  InputNumber,
  Select,
  Upload,
  Carousel,
  Empty,
  Image,
  Popover,
  Table,
  Tabs,
  Tooltip,
  Modal,
  Popconfirm,
  Skeleton,
  Spin,
  Anchor,
  BackTop,
  ConfigProvider,
  Radio,
  Layout,
  Slider,
  Breadcrumb
} from "ant-design-vue";
// version, install, message, notification, Affix, Anchor, AutoComplete, Alert, Avatar, BackTop, Badge, Breadcrumb, Button, Calendar, Card, Collapse, Carousel, Cascader, Checkbox, Col, DatePicker, Divider, Dropdown, Form, Icon, Input, InputNumber, Layout, List, LocaleProvider, Menu, Mentions, Modal, Pagination, Popconfirm, Popover, Progress, Radio, Rate, Row, Select, Slider, Spin, Statistic, Steps, Switch, Table, Transfer, Tree, TreeSelect, Tabs, Tag, TimePicker, Timeline, Tooltip, Upload, Drawer, Skeleton, Comment, ConfigProvider, Empty, Result, Descriptions, PageHeader, Space, Image, Typography,
import "ant-design-vue/dist/antd.css";

export function useAntd(app: App) {
  app.use(Button),
    app.use(Icon),
    app.use(Menu),
    app.use(Pagination),
    app.use(Form),
    app.use(Input),
    app.use(InputNumber),
    app.use(Select),
    app.use(Upload),
    app.use(Carousel),
    app.use(Empty),
    app.use(Image),
    app.use(Popover),
    app.use(Table),
    app.use(Tabs),
    app.use(Tooltip),
    app.use(Modal),
    app.use(Popconfirm),
    app.use(Skeleton),
    app.use(Spin),
    app.use(Anchor),
    app.use(BackTop),
    app.use(ConfigProvider),
    app.use(Radio),
    app.use(Layout),
    app.use(Slider),
    app.use(Breadcrumb)
}
